# Programming with Python

## Episode 1a - Introduction - Analysing Patient Data - Emi

Teaching: 60 min, 
Exercises: 30 min 


Objectives
 
- Assign values to variables. #変数を使う

- Explain what a library is and what libraries are used for. #library とは

- Import a Python library and use the functions it contains.　#import fn を使う

- Read tabular data from a file into a program.　#表のデータを読む

- Select individual values and subsections from data.　#値を選択する

- Perform operations on arrays of data. #データの一覧を使う

## Our Dataset
In this episode we will learn how to work with CSV files in Python. Our dataset contains patient inflammation data - where each row represents a different patient and the column represent inflammation data over a series of days. 

![Data Files](data/inflammation-excel.png)


However, before we discuss how to deal with many data points, let's learn how to work with single data values.



## Variables 変数
Any Python interpreter can be used as a calculator:

```
3 + 5 * 4
```

In [2]:
3 + 5 * 4

23

This is great but not very interesting. To do anything useful with data, we need to assign its value to a variable. In Python, we can assign a value to a variable, using the equals sign ``=``. For example, to assign value 60 to a variable ``weight_kg``, we would execute:　# アサインして、エクスキュート

```
weight_kg = 60
```

In [3]:
weight_kg = 60

From now on, whenever we use ``weight_kg``, Python will substitute the value we assigned to it. In essence, a variable is just a name for a value.　#変数は値の名称

```
weight_kg + 5
```

In [4]:
weight_kg + 5

65

In Python, variable names:

- can include letters, digits, and underscores - `A-z, a-z, _`    #　変数は文字、数字、下線オーケー
- cannot start with a digit　　　　　　　　　　　　　　　　　　　　　　　#　数字からは始められない。　
- are case sensitive.　　　　　　　　　　　　　　　　　　　　　　　　　　　# 大文字、小文字の区別あり

This means that, for example:

数字からはスタートできない。
`weight0` is a valid variable name, whereas `0weight` is not
`weight` and `Weight` are different variables

#### Types of data　　　　データのタイプは３つ：数字、小数点、文字
Python knows various types of data. Three common ones are:

- integer numbers (whole numbers)
- floating point numbers (numbers with a decimal point)
- and strings (of characters).

In the example above, variable `weight_kg` has an integer value of `60`. To create a variable with a floating point value, we can execute:

```
weight_kg = 60.0
```

In [5]:
weight_kg = 60.0

And to create a string we simply have to add single or double quotes around some text, for example: #アポストロフィ〜マークを使ってstring variableをつくる

```
weight_kg_text = 'weight in kilograms:'
```

To display the value of a variable to the screen in Python, we can use the print function: #表示するときはprintで

```
print(weight_kg)
```

In [6]:
weight_kg_text = 'weight in kilograms:'
print(weight_kg)

60.0


We can display multiple things at once using only one print command:　　　# printのカッコ内に複数のことを入れる

```
print(weight_kg_text, weight_kg)
```

In [7]:
print(weight_kg_text, weight_kg)

weight in kilograms: 60.0


Moreover, we can do arithmetic with variables right inside the print function: #printカッコ内で計算できる

```
print('weight in pounds:', 2.2 * weight_kg)
```

In [8]:
print('weight in pounds:', 2.2 * weight_kg)

weight in pounds: 132.0


The above command, however, did not change the value of ``weight_kg``:　# パウンドで計算しても体重の設定は60kgで変化なし

```
print(weight_kg)
```

In [9]:
print(weight_kg)

60.0


To change the value of the ``weight_kg`` variable, we have to assign `weight_kg` a new value using the equals `=` sign:　# 体重を変更するときは新たにアサインする

```
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)
```

In [10]:
weight_kg = 65.0
print('weight in kilograms is now:', weight_kg)

weight in kilograms is now: 65.0


#### Variables as Sticky Notes

A variable is analogous to a sticky note with a name written on it: assigning a value to a variable is like writing a value on the sticky note with a particular name.　# アサインすることはメモ用紙に名前を書き込むようなこと

This means that assigning a value to one variable does not change values of other variables (or sticky notes). For example, let's store the subject's weight in pounds in its own variable:# 他のメモ用紙の名前に変化なし

```
# There are 2.2 pounds per kilogram
weight_lb = 2.2 * weight_kg
print(weight_kg_text, weight_kg, 'and in pounds:', weight_lb)
```

In [11]:
# 1kg　は2.2パウンズ
weight_lb = 2.2 * weight_kg
print('The', weight_kg_text, weight_kg, 'and in pounds:', weight_lb) #weight_kg_textは既にdefined.

The weight in kilograms: 65.0 and in pounds: 143.0


#### Updating a Variable

Variables calculated from other variables do not change their value just because the original variable changed its value (unlike cells in Excel):　#エクセルとは異なり、他の変数(パウンド）と計算しても 体重60kgなら、その設定に変化なし。

```
weight_kg = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)
```

In [12]:
weight_kg = 100.0
print('weight in kilograms is now:', weight_kg, 'and weight in pounds is still:', weight_lb)
# 体重を100kgにしてもpoundsの重さはupdateされてないので、変化なし。)

weight in kilograms is now: 100.0 and weight in pounds is still: 143.0


Since `weight_lb` doesn't *remember* where its value comes from, so it is not updated when we change `weight_kg`.　#パウンド設定はvalueがどこから来たのか覚えてないので、体重を変更してもパウンドでの計算は変化なし。

## Libraries   ライブラリーとは：いろんなツールが入っているもの

Words are useful, but what's more useful are the sentences and stories we build with them (or indeed entire books or whole libraries). Similarly, while a lot of powerful, general tools are built into Python, specialised tools built up from these basic units live in *libraries* that can be called upon when needed.

### Loading data into Python　　　#データを読み取るときはNumpyというlibraryが必要

In order to load our inflammation dataset into Python, we need to access (import in Python terminology) a library called `NumPy` (which stands for Numerical Python). 

In general you should use this library if you want to do fancy things with numbers, especially if you have matrices or arrays. We can import `NumPy` using:

```
import numpy
```

In [13]:
import numpy
# stands for numerical python
# numpy はlibrary の１つ。

Importing a library is like getting a piece of lab equipment out of a storage locker and setting it up on the bench. Libraries provide additional functionality to the basic Python package, much like a new piece of equipment adds functionality to a lab space. Just like in the lab, importing too many libraries can sometimes complicate and slow down your programs - so we only import what we need for each program. Once we've imported the library, we can ask the library to read our data file for us:
- fname　ファイルネーム
- commaで区分けする　delimiter 

```
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
```

In [14]:
numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

The expression `numpy.loadtxt(...)` is a function call that asks Python to run the function `loadtxt` which belongs to the `numpy` library. This dot `.` notation is used everywhere in Python: the thing that appears before the dot contains the thing that appears after.# numpy内のloadtxtというFn  その間にある点（.）で知らせることを「dot notation」という。 

As an example, John Smith is the John that belongs to the Smith family. We could use the dot notation to write his name smith.john, just as `loadtxt` is a function that belongs to the `numpy` library. 

`numpy.loadtxt` has two parameters: the name of the file we want to read and the delimiter that separates values on a line. These both need to be character strings (or strings for short), so we put them in quotes. #loadtxtのカッコ内に２つのパラメタ〜を入れる（読み込むファイル名と区切り方）

The notebook just displays the data since we haven't told it to do anything else with the function's output. (The output is the data we just loaded.) By default, only a few rows and columns are shown (with ... to omit elements when displaying big arrays). To save space, Python displays numbers as 1. instead of 1.0 when there's nothing interesting after the decimal point. # デフォールトで最初と最後の数列のみ表示される。

Our call to `numpy.loadtxt` read our file but didn't save the data in memory. To do that, we need to assign the array to a variable. Just as we can assign a single value to a variable, we can also assign an array of values to a variable using the same syntax. Let's re-run `numpy.loadtxt` and save the returned data:# 表もアサインできる

```
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')　#上のアサインをコピペ
```

In [15]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

This statement doesn't produce any output because we've assigned the output to the variable `data`. If we want to check that the data has been loaded, we can print the variable's value: #表をアサインしてprintで表示

```
print(data)
```

In [16]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


Now that the data is in memory, we can manipulate it. First, let's ask Python what type of thing `data` refers to:

```
print(type(data))
```

In [17]:
# dataタイプを確認する（表面上の）
print(type(data))

<class 'numpy.ndarray'>


The output tells us that data currently refers to an N-dimensional array, the functionality for which is provided by the `NumPy` library. This data correspond to arthritis patients' inflammation. The rows are the individual patients, and the columns are their daily inflammation measurements.＃NumPyが　N-dimensional arrayをだす

#### Data Type

A NumPy array contains one or more elements of the same type. The type function will only tell you that a variable is a NumPy array but won't tell you the type of thing inside the array. We can find out the type of the data contained in the NumPy array. 
#type(data)は表面上、
#data.dtypeは内部のタイプ

```
print(data.dtype)
```

In [18]:
# 実際にどんなデータか見る
print(data.dtype)

float64


This tells us that the NumPy array's elements are floating-point numbers.

With the following command, we can see the array's shape: #シェイプで全体像をつかむ

```
print(data.shape)
```

In [19]:
# (60 rows, 40 columns)
print(data.shape)

(60, 40)


The output tells us that the data array variable contains 60 rows and 40 columns. When we created the variable data to store our arthritis data, we didn't just create the array; we also created information about the array, called members or attributes. This extra information describes data in the same way an adjective describes a noun. data.shape is an attribute of data which describes the dimensions of data. We use the same dotted notation for the attributes of variables that we use for the functions in libraries because they have the same part-and-whole relationship.# カッコ内の情報(メンバー又は、アトリビューツ)、形容詞のようなもの。

If we want to get a single number from the array, we must provide an index in square brackets after the variable name, just as we do in math when referring to an element of a matrix. Our inflammation data has two dimensions, so we will need to use two indices to refer to one specific value:#１箇所のデータを見る時、（　）内に名称と、縦軸と横軸の数値が入ったsquare blacketを入れる。

```
print('first value in data:', data[0, 0])
print('middle value in data:', data[30, 20])
```

In [20]:
#square blacket [] をつかって、１箇所のデータを見る
print('first value in data:', data[0, 0])
print('middle value in data:', data[30, 20])
print('the real middle value in data:', data[29, 19])

first value in data: 0.0
middle value in data: 13.0
the real middle value in data: 16.0


The expression `data[30, 20]` accesses the element at row 30, column 20. While this expression may not surprise you, `data[0, 0]` might. # 縦30横20の値は普通だけど、[0,0]のデータはびっくりする??

#### Zero Indexing

Programming languages like Fortran, MATLAB and R start counting at 1 because that's what human beings have done for thousands of years. Languages in the C family (including C++, Java, Perl, and Python) count from 0 because it represents an offset from the first value in the array (the second value is offset by one index from the first value). This is closer to the way that computers represent arrays (if you are interested in the historical reasons behind counting indices from zero, you can read Mike Hoye's blog post). # 0から始まるコンピューター言語

As a result, if we have an M×N array in Python, its indices go from 0 to M-1 on the first axis and 0 to N-1 on the second. It takes a bit of getting used to, but one way to remember the rule is that the index is how many steps we have to take from the start to get the item we want.　＃stepsの回数だと考える

#### In the Corner

What may also surprise you is that when Python displays an array, it shows the element with index `[0, 0]` in the upper left corner rather than the lower left. This is consistent with the way mathematicians draw matrices but different from the Cartesian coordinates（直交座標系）. The indices are (row, column) instead of (column, row) for the same reason, which can be confusing when plotting data.#直交座標系で、必ず左上から始まる。

#### Slicing data

An index like `[30, 20]` selects a single element of an array, but we can select whole sections as well. For example, we can select the first ten days (columns) of values for the first four patients (rows) like this:＃データは１箇所のみではなく、最初から４人目までの、最初の10日間などスライスで見ることができる。

```
print(data[0:4, 0:10])
```

In [21]:
print(data[0:4, 0:10])
# 最初のスライスを見る

[[0. 0. 1. 3. 1. 2. 4. 7. 8. 3.]
 [0. 1. 2. 1. 2. 1. 3. 2. 2. 6.]
 [0. 1. 1. 3. 3. 2. 6. 2. 5. 9.]
 [0. 0. 2. 0. 4. 2. 2. 1. 6. 7.]]


The slice `[0:4]` means, *Start at index 0 and go up to, but not including, index 4*. ＃０から数えて４番目は５人目で、[0,4]の4は省くので、５人目は省く。最後は NOT INCLUDED

Again, the up-to-but-not-including takes a bit of getting used to, but the rule is that the difference between the upper and lower bounds is the number of values in the slice.# 中間からのスライス可能

Also, we don't have to start slices at `0`:

```
print(data[5:10, 0:10])
```

In [22]:
print(data[5:10, 0:10])
# 中間のスライスを見る

[[0. 0. 1. 2. 2. 4. 2. 1. 6. 4.]
 [0. 0. 2. 2. 4. 2. 2. 5. 5. 8.]
 [0. 0. 1. 2. 3. 1. 2. 3. 5. 3.]
 [0. 0. 0. 3. 1. 5. 6. 5. 5. 8.]
 [0. 1. 1. 2. 1. 3. 5. 3. 5. 8.]]


and we don't have to include the upper or lower bound on the slice. ＃最初の０と、表の最後の数はomit可能

If we don't include the lower bound, Python uses 0 by default; if we don't include the upper, the slice runs to the end of the axis, and if we don't include either (i.e., if we just use `:` on its own), the slice includes everything:＃最初の数字がなければデフォルトで０から始まる。最後の数字がなければ、スライスは最後まで続く。両方の数字がなければ、全てをスライス。

```
small = data[:3, 36:]
print('small is:')
print(small)
```

In [23]:
small = data[:3, 36:]
print('small is:')
print(small)

small is:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]


The above example selects rows 0 through 2 and columns 36 through to the end of the array.　#[：３、とは、縦０〜２までのこと。36:]とは、３６〜最後まで、という意味。

thus small （小セクションのスライス）is:
```
[[ 2.  3.  0.  0.]
 [ 1.  1.  0.  1.]
 [ 2.  2.  1.  1.]]
```

Arrays also know how to perform common mathematical operations on their values. The simplest operations with data are arithmetic: addition, subtraction, multiplication, and division. When you do such operations on arrays, the operation is done element-by-element. Thus:# 表で＋ーx/ ができる。

```
doubledata = data * 2.0
```

In [27]:
doubledata = data * 2.0
#まずdefine

will create a new array doubledata each element of which is twice the value of the corresponding element in data:

```
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])
```

In [28]:
#上で　defineしたdoubledataを使う。
print('original:')
print(data[:3, 36:])
print('doubledata:')
print(doubledata[:3, 36:])

original:
[[2. 3. 0. 0.]
 [1. 1. 0. 1.]
 [2. 2. 1. 1.]]
doubledata:
[[4. 6. 0. 0.]
 [2. 2. 0. 2.]
 [4. 4. 2. 2.]]


If, instead of taking an array and doing arithmetic with a single value (as above), you did the arithmetic operation with another array of the same shape, the operation will be done on corresponding elements of the two arrays. Thus:

```
tripledata = doubledata + data
```

In [29]:
tripledata = doubledata + data
# ３倍をdefineする 

will give you an array where `tripledata[0,0]` will equal `doubledata[0,0]` plus `data[0,0]`, and so on for all other elements of the arrays.

```
print('tripledata:')
print(tripledata[:3, 36:])
```

In [30]:
# 上でdefineした　tripledataを使う
print('tripledata:')
print(tripledata[:3, 36:])

tripledata:
[[6. 9. 0. 0.]
 [3. 3. 0. 3.]
 [6. 6. 3. 3.]]


## Exercises

### Variables

What values do the variables mass and age have after each statement in the following program? 
```
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass, age)
```
Test your answers by executing the commands.

In [31]:
mass = 47.5
age = 122
mass = mass * 2.0
age = age - 20
print(mass, age)

95.0 102


Solution:最初にアサインしたmassとageは消える。二度目のアサインがoverrideしてるから。

### Sorting Out References

What does the following program print out?
```
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)
```

In [32]:
first, second = 'Grace', 'Hopper'
third, fourth = second, first
print(third, fourth)

Hopper Grace


Solution:代名詞を別の代名詞にアサインすることで順番が入れ替わる。thirdとfourthにアサインするときに、firstとsecondの順を入れ替えることで、printした時の順が最初の順の逆となる。

### Slicing Strings
A section of an array is called a slice. We can take slices of character strings as well:　#序列の１部をスライスという。単語のスライスを行う。
```
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
```

What is the value of `element[:4]` ? What about `element[4:]`? Or `element[:]` ?

What about `element[-1]` and `element[-2]` ?

In [35]:
element = 'oxygen'
print('first three characters:', element[0:3])
print('last three characters:', element[3:6])
print(element[:4])
print(element[4:])
print(element[:])
print(element[-1])
print(element[-2])
print(element[:-2])

first three characters: oxy
last three characters: gen
oxyg
en
oxygen
n
e
oxyg


Solution:マイナスを使うときは、０はなく、最後のアルファベットが−１になり、countingが逆方向に。文字列はそのまま。

Given those answers, explain what `element[1:-1]` does.

In [36]:
print(element[1:-1])

xyge


Solution: １はx（左から２つ目、0,1の1）で、−１はnで、nを含まないため、その手前のe（右から２つ目、−２）がくる

### Thin Slices 薄切りはなし

The expression `element[3:3]` produces an empty string, i.e., a string that contains no characters. If data holds our array of patient data, what does `data[3:3, 4:4]` produce? What about `data[3:3, :]` ?

In [37]:
#print([3:3]) --> error 
#print([3:3, 4:4]) --> error
#print([3:3, :]) --> error 

Solution:左で数字を指定しても、右のattributesは含まないNOT INCLUDEDだから、同じ数字は矛盾するため。

## Key Points
Import a library into a program using import library_name.　# import ~~ でインポートする

Use the numpy library to work with arrays in Python.　# 表にはNumpyを使う

Use `variable` `=` `value` to assign a value to a variable in order to record it in memory.#変数＝値のパターンでアサインする

Variables are created on demand whenever a value is assigned to them.# 値をアサインして変数を作る

Use `print(something)` to display the value of something.　# printで表示する

The expression `array.shape` gives the shape of an array. # shapeで表の全体像を

Use `array[x, y]` to select a single element from a 2D array.# array[x,y]で表の１箇所を見る

Array indices start at 0, not 1.# 表は０からはじまる。

Use `low:high` to specify a slice that includes the indices from low to high-1. # low:highを使って、範囲を設定する

All the indexing and slicing that works on arrays also works on strings.# 表で使えるindexingとスライスは文字でも可能。

Use `#` and some kind of explanation to add comments to programs.# このマークでコメントを残す

# Save, and version control your changes

- save your work: `File -> Save`
- add all your changes to your local repository: `Terminal -> git add .`
- commit your updates a new Git version:  `Terminal -> git commit -m "End of Episode 1"`
- push your latest commits to GitHub: `Terminal -> git push`